import type { Clock } from './clock.js';
import { systemClock } from './clock.js';
import type { PipeMode, PipeRole } from '../types.js';

// ── Delivery state machine ──────────────────────────────────────────────────

/** Delivery lifecycle for a single stage assignment.
 *  assigned → notified → fetched → submitted
 *                ↓           ↓
 *            (re-notify)   (submitted)
 *                ↓
 *          expired / cancelled */
export type DeliveryState =
  | 'assigned'     // lease granted, notification not yet sent
  | 'notified'     // compact notification delivered to PTY
  | 'fetched'      // assignee called pipe_read_output (implicit ack)
  | 'submitted'    // assignee submitted via pipe_submit
  | 'expired'      // re-notify attempts exhausted or deadline passed
  | 'cancelled';   // pipe cancelled or assignee reassigned

export interface DeliveryRecord {
  pipeId: string;
  assignee: string;
  stage?: number;
  role: string;               // 'handoff' | 'fan-out-request' | 'synth-request'
  state: DeliveryState;
  /** Full payload body generated by the reducer — stored here for fetch retrieval. */
  payload: string;
  /** Number of PTY notification attempts so far. */
  notifyAttempts: number;
  /** Maximum notification attempts before escalating / expiring. */
  maxNotifyAttempts: number;
  /** Milliseconds between re-notify attempts. */
  renotifyIntervalMs: number;
  // Timestamps (ISO)
  assignedAt: string;
  notifiedAt: string | null;
  fetchedAt: string | null;
  submittedAt: string | null;
  lastNotifyAttemptAt: string | null;
}

// ── Configuration ───────────────────────────────────────────────────────────

export const DEFAULT_MAX_NOTIFY_ATTEMPTS = 3;
export const DEFAULT_RENOTIFY_INTERVAL_MS = 30_000; // 30 seconds

export interface DeliveryConfig {
  maxNotifyAttempts?: number;
  renotifyIntervalMs?: number;
}

// ── Storage ─────────────────────────────────────────────────────────────────

// Key: "projectId:pipeId:assignee"
const deliveryRecords = new Map<string, DeliveryRecord>();

// Re-notify timers: same key → NodeJS.Timeout
const renotifyTimers = new Map<string, ReturnType<typeof setTimeout>>();

function deliveryKey(pipeId: string, assignee: string, projectId: string | null): string {
  return `${projectId ?? '__none__'}:${pipeId}:${assignee}`;
}

// ── Injectable clock ────────────────────────────────────────────────────────

let _clock: Clock = systemClock;

export function setDeliveryClock(clock: Clock): void {
  _clock = clock;
}

// ── Delivery lifecycle ──────────────────────────────────────────────────────

/** Create a delivery record when a lease is granted and the reducer action is ready. */
export function createDelivery(
  pipeId: string,
  assignee: string,
  role: string,
  payload: string,
  projectId: string | null,
  stage?: number,
  config?: DeliveryConfig,
): DeliveryRecord {
  const key = deliveryKey(pipeId, assignee, projectId);

  const record: DeliveryRecord = {
    pipeId,
    assignee,
    stage,
    role,
    state: 'assigned',
    payload,
    notifyAttempts: 0,
    maxNotifyAttempts: config?.maxNotifyAttempts ?? DEFAULT_MAX_NOTIFY_ATTEMPTS,
    renotifyIntervalMs: config?.renotifyIntervalMs ?? DEFAULT_RENOTIFY_INTERVAL_MS,
    assignedAt: _clock.isoNow(),
    notifiedAt: null,
    fetchedAt: null,
    submittedAt: null,
    lastNotifyAttemptAt: null,
  };

  deliveryRecords.set(key, record);
  return record;
}

/** Record that the compact notification was delivered to PTY.
 *  Returns false if the delivery is not in a valid state for notification. */
export function recordNotification(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): boolean {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return false;
  if (record.state === 'submitted' || record.state === 'expired' || record.state === 'cancelled') {
    return false;
  }

  const now = _clock.isoNow();
  record.state = 'notified';
  record.notifyAttempts += 1;
  record.notifiedAt = record.notifiedAt ?? now;
  record.lastNotifyAttemptAt = now;
  return true;
}

/** Record that the assignee fetched the payload (called when pipe_read_output is invoked).
 *  This serves as an implicit acknowledgment. */
export function recordFetch(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): boolean {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return false;
  if (record.state === 'submitted' || record.state === 'expired' || record.state === 'cancelled') {
    return false;
  }

  record.state = 'fetched';
  record.fetchedAt = _clock.isoNow();

  // Cancel any pending re-notify timer — assignee is alive
  cancelRenotifyTimer(pipeId, assignee, projectId);
  return true;
}

/** Record that the assignee submitted their output. */
export function recordSubmission(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): boolean {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return false;
  if (record.state === 'expired' || record.state === 'cancelled') {
    return false;
  }

  record.state = 'submitted';
  record.submittedAt = _clock.isoNow();

  cancelRenotifyTimer(pipeId, assignee, projectId);
  return true;
}

/** Mark a delivery as cancelled (pipe cancelled or assignee reassigned). */
export function cancelDelivery(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): boolean {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return false;
  if (record.state === 'submitted') return false; // already done

  record.state = 'cancelled';
  cancelRenotifyTimer(pipeId, assignee, projectId);
  return true;
}

/** Mark a delivery as expired (re-notify attempts exhausted). */
export function expireDelivery(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): boolean {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return false;
  if (record.state === 'submitted' || record.state === 'cancelled') return false;

  record.state = 'expired';
  cancelRenotifyTimer(pipeId, assignee, projectId);
  return true;
}

// ── Re-notify logic ─────────────────────────────────────────────────────────

export type RenotifyCallback = (pipeId: string, assignee: string, projectId: string | null) => void;

/** Start the re-notify timer for a delivery.
 *  If the assignee hasn't fetched the payload within renotifyIntervalMs,
 *  the callback fires to re-deliver the notification. */
export function startRenotifyTimer(
  pipeId: string,
  assignee: string,
  projectId: string | null,
  callback: RenotifyCallback,
): void {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return;
  if (record.state !== 'notified') return;

  const key = deliveryKey(pipeId, assignee, projectId);

  // Clear any existing timer
  cancelRenotifyTimer(pipeId, assignee, projectId);

  const timer = setTimeout(() => {
    renotifyTimers.delete(key);
    handleRenotifyTick(pipeId, assignee, projectId, callback);
  }, record.renotifyIntervalMs);

  // Don't prevent process exit
  if (typeof timer === 'object' && 'unref' in timer) timer.unref();

  renotifyTimers.set(key, timer);
}

/** Internal: handle a re-notify tick. Checks whether to re-notify or expire. */
function handleRenotifyTick(
  pipeId: string,
  assignee: string,
  projectId: string | null,
  callback: RenotifyCallback,
): void {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record) return;

  // Only re-notify if still in 'notified' state (not fetched, submitted, cancelled, etc.)
  if (record.state !== 'notified') return;

  if (record.notifyAttempts >= record.maxNotifyAttempts) {
    // Exhausted — expire this delivery
    expireDelivery(pipeId, assignee, projectId);
    return;
  }

  // Fire the re-notify callback (caller re-delivers the compact notification)
  callback(pipeId, assignee, projectId);
}

function cancelRenotifyTimer(pipeId: string, assignee: string, projectId: string | null): void {
  const key = deliveryKey(pipeId, assignee, projectId);
  const timer = renotifyTimers.get(key);
  if (timer) {
    clearTimeout(timer);
    renotifyTimers.delete(key);
  }
}

// ── Queries ─────────────────────────────────────────────────────────────────

/** Get the delivery record for a specific assignment. */
export function getDelivery(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): DeliveryRecord | undefined {
  return deliveryRecords.get(deliveryKey(pipeId, assignee, projectId));
}

/** Get the stored payload for a delivery (used by fetch surface). */
export function getDeliveryPayload(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): string | undefined {
  return getDelivery(pipeId, assignee, projectId)?.payload;
}

/** Check if a delivery needs re-notification (notified but not fetched, timer-eligible). */
export function needsRenotify(
  pipeId: string,
  assignee: string,
  projectId: string | null,
): boolean {
  const record = getDelivery(pipeId, assignee, projectId);
  if (!record || record.state !== 'notified') return false;
  if (record.notifyAttempts >= record.maxNotifyAttempts) return false;

  // Check if enough time has passed since last notification attempt
  if (!record.lastNotifyAttemptAt) return false;
  const elapsed = _clock.now() - new Date(record.lastNotifyAttemptAt).getTime();
  return elapsed >= record.renotifyIntervalMs;
}

/** Get all active (non-terminal) delivery records for a pipe. */
export function getActiveDeliveries(
  pipeId: string,
  projectId: string | null,
): DeliveryRecord[] {
  const results: DeliveryRecord[] = [];
  const prefix = `${projectId ?? '__none__'}:${pipeId}:`;
  for (const [key, record] of deliveryRecords) {
    if (key.startsWith(prefix) && record.state !== 'submitted' && record.state !== 'expired' && record.state !== 'cancelled') {
      results.push(record);
    }
  }
  return results;
}

/** Cancel all active deliveries for a pipe (called when pipe is cancelled/failed). */
export function cancelAllDeliveries(pipeId: string, projectId: string | null): void {
  const prefix = `${projectId ?? '__none__'}:${pipeId}:`;
  for (const [key, record] of deliveryRecords) {
    if (key.startsWith(prefix) && record.state !== 'submitted') {
      record.state = 'cancelled';
      // Cancel associated timer
      const timer = renotifyTimers.get(key);
      if (timer) {
        clearTimeout(timer);
        renotifyTimers.delete(key);
      }
    }
  }
}

/** Cancel all deliveries for a specific assignee across all pipes (called when participant leaves). */
export function cancelDeliveriesForAssignee(assignee: string, projectId: string | null): void {
  const suffix = `:${assignee}`;
  const prefix = `${projectId ?? '__none__'}:`;
  for (const [key, record] of deliveryRecords) {
    if (key.startsWith(prefix) && key.endsWith(suffix) && record.state !== 'submitted') {
      record.state = 'cancelled';
      const timer = renotifyTimers.get(key);
      if (timer) {
        clearTimeout(timer);
        renotifyTimers.delete(key);
      }
    }
  }
}

// ── Compact notification formatting ─────────────────────────────────────────

export interface CompactNotification {
  /** The compact text to inject into PTY. */
  body: string;
  /** Pipe metadata for the message envelope. */
  pipe: {
    pipeId: string;
    mode: PipeMode;
    role: PipeRole;
    stage?: number;
    targetAssignee: string;
  };
}

/** Format a compact assignment notification for PTY delivery.
 *  This replaces the full payload body — the LLM must fetch the full content
 *  via pipe_read_output after receiving this notification. */
export function formatCompactNotification(
  pipeId: string,
  mode: PipeMode,
  actionType: 'handoff' | 'fan-out-request' | 'synth-request',
  targetAssignee: string,
  totalStages: number,
  stage?: number,
  chatRole?: string | null,
): CompactNotification {
  const roleMap: Record<string, PipeRole> = {
    'handoff': 'handoff',
    'fan-out-request': 'fan-out-request',
    'synth-request': 'synth-request',
  };
  const role = roleMap[actionType];

  let header: string;
  let guidance: string;
  const roleSuffix = chatRole ? ` | Your role: ${chatRole}` : '';

  if (actionType === 'handoff') {
    const isLast = stage === totalStages;
    header = `#pipe-${pipeId} [linear | stage ${stage}/${totalStages} | @${targetAssignee}${roleSuffix}]`;
    guidance = isLast
      ? 'Final stage — your response goes to the user.'
      : 'Your output passes to the next stage.';
  } else if (actionType === 'fan-out-request') {
    header = `#pipe-${pipeId} [${mode} | fan-out | @${targetAssignee}${roleSuffix}]`;
    guidance = 'Provide your independent analysis. Other participants answer in parallel.';
  } else {
    header = `#pipe-${pipeId} [${mode} | synthesizer | @${targetAssignee}${roleSuffix}]`;
    guidance = 'Synthesize the fan-out outputs into a unified response.';
  }

  const assignmentLine = `Inspect assignment: pipe_get_assignment(pipeId="${pipeId}")`;
  const fetchLine = `Read stage input: pipe_read_output(pipeId="${pipeId}")`;
  const submitLine = `Submit: pipe_submit(pipeId="${pipeId}", content="<your output>")\nDo not use chat_send. Submit once, then wait.`;

  const body = `${header}\n\n${guidance}\n\n${assignmentLine}\n${fetchLine}\n\n${submitLine}`;

  return {
    body,
    pipe: { pipeId, mode, role, stage, targetAssignee },
  };
}

/** Get delivery records where notification attempts are exhausted or state is expired.
 *  These represent assignments that failed to reach the assignee. */
export function getExhaustedDeliveries(projectId: string | null): DeliveryRecord[] {
  const results: DeliveryRecord[] = [];
  const prefix = `${projectId ?? '__none__'}:`;
  for (const [key, record] of deliveryRecords) {
    if (!key.startsWith(prefix)) continue;
    // Expired deliveries (retries exhausted or explicitly expired)
    if (record.state === 'expired') {
      results.push(record);
      continue;
    }
    // Still active but retries exhausted — stuck in notified state
    if (record.state === 'notified' && record.notifyAttempts >= record.maxNotifyAttempts) {
      results.push(record);
    }
  }
  return results;
}

// ── Test helper ─────────────────────────────────────────────────────────────

/** Reset all in-memory delivery state. For testing only. */
export function _resetForTest(): void {
  deliveryRecords.clear();
  for (const timer of renotifyTimers.values()) {
    clearTimeout(timer);
  }
  renotifyTimers.clear();
  _clock = systemClock;
}
